packages:
  - .
  - packages/*

allowBuilds:
  better-sqlite3: true
  protobufjs: true

minimumReleaseAgeExclude:
  - '@photon-ai/advanced-imessage@0.12.0'
  - '@spectrum-ts/core@8.2.1'
  - '@spectrum-ts/imessage@8.2.1'
  - '@spectrum-ts/slack@8.2.1'
  - '@spectrum-ts/telegram@8.2.1'
  - '@spectrum-ts/terminal@8.2.1'
  - '@spectrum-ts/whatsapp-business@8.2.1'
  - spectrum-ts@8.2.1
  - '@photon-ai/whatsapp-business@0.2.0'

onlyBuiltDependencies:
  - better-sqlite3
  - protobufjs
